version: '2'

services:
  nexus:
    container_name: nexus-container
    image: sonatype/nexus3:3.26.1
    ports:
      - "8080:8081"
      - "8082:8082"
    volumes:
      - nexus-data:/nexus-data

  nginx:
    container_name: nginx-container
    image: nginx:latest
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/nexus.crt:/etc/nginx/ssl.crt
      - ./certs/nexus.key:/etc/nginx/ssl.key
    ports:
      - "80:80"
      - "443:443"

  gitlab:
    container_name: gitlab-ce
    hostname: gitlab.4fasters.com
    image: gitlab/gitlab-ce:13.3.1-ce.0
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.4fasters.com:8083'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - "8083:8083"
      - "2224:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  gitlab-runner:
    container_name: gitlab-runner
    restart: always
    image: gitlab/gitlab-runner:v13.3.1
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nexus-data:
  gitlab-config:
  gitlab-log:
  gitlab-data:
  gitlab-runner-config:
      