apiVersion: v1
kind: Service
metadata:
  name: java-webapp-svc
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
  namespace: java-webapp
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: java-webapp
  type: LoadBalancer