apiVersion: v1
data:
  secretkey: S3dyTlk5TFZuWnk0ZUdzMWgwblMxVjNaUldUK0IrM2lIUm1mM205Q0pHSkZnVTZuNGQwejREaDJqVXhZVk93cQpxRXo4dTYwVkNXalJzeHkvNFl3eEMyS3VudlByd2NnVEFKa1V1cVFPYnRaRjdGUUJvVGh5Y3l1a0JocmdueHJECjFhaUQ4aytrdHJ0aktkWkZkdXBpREszWFVycW9lbWVYcVVEU1BDYWVlSWM9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
